// extra genre rows for specific providers, genreId format varies per provider (numeric ids vs full urls)
export interface CustomSection {
  label: string;
  genreId: string;
}

export const CUSTOM_HOME_SECTIONS: Record<string, CustomSection[]> = {
  StreamingCommunity: [
    { label: "Azione", genreId: "4" },
    { label: "Romance", genreId: "15" },
    { label: "Animazione", genreId: "19" },
    { label: "Sci-Fi & Fantasy", genreId: "3" },
    { label: "Crime", genreId: "2" },
    { label: "Horror", genreId: "7" },
    { label: "Korean Drama", genreId: "26" },
    { label: "Reality", genreId: "18" },
  ],
  "StreamingCommunity (EN)": [
    { label: "Azione", genreId: "4" },
    { label: "Romance", genreId: "15" },
    { label: "Animazione", genreId: "19" },
    { label: "Sci-Fi & Fantasy", genreId: "3" },
    { label: "Crime", genreId: "2" },
    { label: "Horror", genreId: "7" },
    { label: "Korean Drama", genreId: "26" },
    { label: "Reality", genreId: "18" },
  ],
  Altadefinizione01: [
    { label: "Azione", genreId: "https://altadefinizione-01.fun/azione/" },
    { label: "Romance", genreId: "https://altadefinizione-01.fun/romantico/" },
    { label: "Animazione", genreId: "https://altadefinizione-01.fun/animazione/" },
    { label: "Horror", genreId: "https://altadefinizione-01.fun/horror/" },
  ],
  AnimeUnity: [
    { label: "Isekai", genreId: "53" },
    { label: "Shounen", genreId: "34" },
    { label: "Seinen", genreId: "49" },
    { label: "Slice of Life", genreId: "50" },
    { label: "Mecha", genreId: "38" },
    { label: "Romance", genreId: "17" },
    { label: "Sci-Fi", genreId: "40" },
    { label: "Sport", genreId: "27" },
    { label: "Supernatural", genreId: "42" },
    { label: "Horror", genreId: "3" },
  ],
  CB01: [
    { label: "Azione", genreId: "https://cb01official.uno/category/azione/" },
    { label: "Commedia", genreId: "https://cb01official.uno/category/commedia/" },
    { label: "Horror", genreId: "https://cb01official.uno/category/horror/" },
    { label: "Thriller", genreId: "https://cb01official.uno/category/thriller/" },
    { label: "Romantico", genreId: "https://cb01official.uno/category/sentimentale/" },
    { label: "Fantascienza", genreId: "https://cb01official.uno/category/fantascienza/" },
    { label: "Animazione", genreId: "https://cb01official.uno/category/animazione/" },
  ],
  Ridomovies: [
    { label: "Action", genreId: "action" },
    { label: "Comedy", genreId: "comedy" },
    { label: "Horror", genreId: "horror" },
    { label: "Romance", genreId: "romance" },
    { label: "Thriller", genreId: "thriller" },
    { label: "Sci-Fi", genreId: "sci-fi" },
    { label: "Crime", genreId: "crime" },
    { label: "Animation", genreId: "animation" },
  ],
  Fanpelis: [
    { label: "Acción", genreId: "accion" },
    { label: "Comedia", genreId: "comedia" },
    { label: "Terror", genreId: "terror" },
    { label: "Romance", genreId: "romance" },
    { label: "Suspenso", genreId: "suspense" },
    { label: "Ciencia Ficción", genreId: "ciencia-ficcion" },
    { label: "Crimen", genreId: "crimen" },
    { label: "Animación", genreId: "animacion" },
  ],
  HDFilme: [
    { label: "Action", genreId: "https://hdfilme.win/action/" },
    { label: "Komödie", genreId: "https://hdfilme.win/komodie/" },
    { label: "Horror", genreId: "https://hdfilme.win/horror/" },
    { label: "Romantik", genreId: "https://hdfilme.win/romantik/" },
    { label: "Thriller", genreId: "https://hdfilme.win/thriller/" },
    { label: "Sci-Fi", genreId: "https://hdfilme.win/sci-fi/" },
    { label: "Krimi", genreId: "https://hdfilme.win/krimi/" },
    { label: "Animation", genreId: "https://hdfilme.win/animation/" },
  ],
  // id format is "Name|catid" - catid comes straight off the site's own genre menu
  Kidraz: [
    { label: "Action", genreId: "Action|1" },
    { label: "Comédie", genreId: "Comédie|6" },
    { label: "Horreur", genreId: "Horreur|9" },
    { label: "Thriller", genreId: "Thriller|12" },
    { label: "Science-Fiction", genreId: "Science-Fiction|11" },
    { label: "Policier", genreId: "Policier|10" },
    { label: "Fantastique", genreId: "Fantastique|8" },
    { label: "Aventure", genreId: "Aventure|4" },
  ],
  PelisflixHD: [
    { label: "Acción", genreId: "https://pelisflixhd.win/genero/accion" },
    { label: "Comedia", genreId: "https://pelisflixhd.win/genero/comedia" },
    { label: "Terror", genreId: "https://pelisflixhd.win/genero/terror" },
    { label: "Romance", genreId: "https://pelisflixhd.win/genero/romance" },
    { label: "Suspenso", genreId: "https://pelisflixhd.win/genero/suspense" },
    { label: "Ciencia Ficción", genreId: "https://pelisflixhd.win/genero/ciencia-ficcion" },
    { label: "Crimen", genreId: "https://pelisflixhd.win/genero/crimen" },
    { label: "Animación", genreId: "https://pelisflixhd.win/genero/animacion" },
  ],
  // getGenre delegates straight to TMDb3.Discover with the id as the genre param, so these are plain TMDB genre ids
  Cinemove: [
    { label: "Action", genreId: "28" },
    { label: "Comedy", genreId: "35" },
    { label: "Horror", genreId: "27" },
    { label: "Romance", genreId: "10749" },
    { label: "Thriller", genreId: "53" },
    { label: "Sci-Fi", genreId: "878" },
    { label: "Crime", genreId: "80" },
    { label: "Animation", genreId: "16" },
  ],
  "Cuevana 3": [
    { label: "Acción", genreId: "accion" },
    { label: "Comedia", genreId: "comedia" },
    { label: "Terror", genreId: "terror" },
    { label: "Romance", genreId: "romance" },
    { label: "Suspenso", genreId: "suspense" },
    { label: "Ciencia Ficción", genreId: "ciencia-ficcion" },
    { label: "Crimen", genreId: "crimen" },
    { label: "Animación", genreId: "animacion" },
  ],
  // same numeric scheme as TMDB, pulled straight from the site's own api/genres endpoint
  Einschalten: [
    { label: "Action", genreId: "28" },
    { label: "Komödie", genreId: "35" },
    { label: "Horror", genreId: "27" },
    { label: "Liebesfilm", genreId: "10749" },
    { label: "Thriller", genreId: "53" },
    { label: "Science Fiction", genreId: "878" },
    { label: "Krimi", genreId: "80" },
    { label: "Animation", genreId: "16" },
  ],
  Filmo: [
    { label: "Action", genreId: "action" },
    { label: "Comedy", genreId: "comedy" },
    { label: "Horror", genreId: "horror" },
    { label: "Romance", genreId: "romance" },
    { label: "Thriller", genreId: "thriller" },
    { label: "Science Fiction", genreId: "science-fiction" },
    { label: "Crime", genreId: "crime" },
    { label: "Animation", genreId: "animation" },
  ],
  FshareTV: [
    { label: "Action", genreId: "Action" },
    { label: "Comedy", genreId: "Comedy" },
    { label: "Horror", genreId: "Horror" },
    { label: "Romance", genreId: "Romance" },
    { label: "Thriller", genreId: "Thriller" },
    { label: "Sci-Fi", genreId: "Sci-Fi" },
    { label: "Crime", genreId: "Crime" },
    { label: "Animation", genreId: "Animation" },
  ],
  // kids' cartoon site organized by network/studio brand rather than genre
  "La Cartoons": [
    { label: "Nickelodeon", genreId: "1" },
    { label: "Cartoon Network", genreId: "2" },
    { label: "Hanna Barbera", genreId: "4" },
    { label: "Disney", genreId: "5" },
    { label: "Warner Channel", genreId: "6" },
    { label: "Marvel", genreId: "7" },
  ],
  MEGAKino: [
    { label: "Action", genreId: "/action/" },
    { label: "Comedy", genreId: "/comedy/" },
    { label: "Horror", genreId: "/horror/" },
    { label: "Romance", genreId: "/romance/" },
    { label: "Thriller", genreId: "/thriller/" },
    { label: "Science Fiction", genreId: "/science-fiction/" },
    { label: "Crime", genreId: "/crime/" },
    { label: "Fantasy", genreId: "/fantasy/" },
  ],
  "Series Turcas": [
    { label: "Acción", genreId: "/generos/accion/" },
    { label: "Comedia", genreId: "/generos/comedia/" },
    { label: "Romance", genreId: "/generos/romance/" },
    { label: "Thriller", genreId: "/generos/thriller/" },
    { label: "Crimen", genreId: "/generos/crimen/" },
    { label: "Drama", genreId: "/generos/drama/" },
    { label: "Misterio", genreId: "/generos/misterio/" },
    { label: "Aventura", genreId: "/generos/aventura/" },
  ],
  SeriesFlix: [
    { label: "Acción", genreId: "accion" },
    { label: "Comedia", genreId: "comedia" },
    { label: "Terror", genreId: "terror" },
    { label: "Aventura", genreId: "aventura" },
    { label: "Ciencia Ficción", genreId: "ciencia-ficcion" },
    { label: "Crimen", genreId: "crimen" },
    { label: "Animación", genreId: "animacion" },
    { label: "Drama", genreId: "drama" },
  ],
  "TMDB (ITA)": [
    { label: "Azione", genreId: "28" },
    { label: "Commedia", genreId: "35" },
    { label: "Horror", genreId: "27" },
    { label: "Romance", genreId: "10749" },
    { label: "Thriller", genreId: "53" },
    { label: "Fantascienza", genreId: "878" },
    { label: "Crime", genreId: "80" },
    { label: "Animazione", genreId: "16" },
  ],
  HiAnime: [
    { label: "Isekai", genreId: "isekai" },
    { label: "Shounen", genreId: "shounen" },
    { label: "Seinen", genreId: "seinen" },
    { label: "Slice of Life", genreId: "slice-of-life" },
    { label: "Mecha", genreId: "mecha" },
    { label: "Harem", genreId: "harem" },
    { label: "Supernatural", genreId: "supernatural" },
    { label: "Psychological", genreId: "psychological" },
  ],
  AnimeWorld: [
    { label: "Shounen", genreId: "shounen" },
    { label: "Seinen", genreId: "seinen" },
    { label: "Slice of Life", genreId: "slice-of-life" },
    { label: "Mecha", genreId: "mecha" },
    { label: "Harem", genreId: "harem" },
    { label: "Fantasy", genreId: "fantasy" },
    { label: "Sci-Fi", genreId: "sci-fi" },
    { label: "Psychological", genreId: "psychological" },
  ],
  AniWorld: [
    { label: "Shounen", genreId: "fighting-shounen" },
    { label: "Mecha", genreId: "mecha" },
    { label: "Harem", genreId: "harem" },
    { label: "Slice of Life", genreId: "alltagsleben" },
    { label: "Fantasy", genreId: "fantasy" },
    { label: "Sci-Fi", genreId: "scifi" },
    { label: "Romance", genreId: "romanze" },
    { label: "Sport", genreId: "sport" },
  ],
  Anikoto: [
    { label: "Isekai", genreId: "isekai" },
    { label: "Shounen", genreId: "shounen" },
    { label: "Seinen", genreId: "seinen" },
    { label: "Mecha", genreId: "mecha" },
    { label: "Harem", genreId: "harem" },
    { label: "Psychological", genreId: "psychological" },
    { label: "Sci-Fi", genreId: "sci-fi" },
    { label: "Supernatural", genreId: "supernatural" },
  ],
  TioAnime: [
    { label: "Mecha", genreId: "mecha" },
    { label: "Seinen", genreId: "seinen" },
    { label: "Shounen", genreId: "shounen" },
    { label: "Shoujo", genreId: "shoujo" },
    { label: "Romance", genreId: "romance" },
    { label: "Sobrenatural", genreId: "sobrenatural" },
    { label: "Terror", genreId: "terror" },
    { label: "Fantasía", genreId: "fantasia" },
  ],
  Latanime: [
    { label: "Mecha", genreId: "mecha" },
    { label: "Seinen", genreId: "seinen" },
    { label: "Shonen", genreId: "shonen" },
    { label: "Shojo", genreId: "shojo" },
    { label: "Harem", genreId: "harem" },
    { label: "Sobrenatural", genreId: "sobrenatural" },
    { label: "Psicológico", genreId: "psicologico" },
    { label: "Recuerdos de la Vida", genreId: "recuerdos-de-la-vida" },
  ],
  AnimeSaturn: [
    { label: "Isekai", genreId: "isekai" },
    { label: "Shounen", genreId: "shounen" },
    { label: "Seinen", genreId: "seinen" },
    { label: "Mecha", genreId: "mecha" },
    { label: "Harem", genreId: "harem" },
    { label: "Psicologico", genreId: "psicologico" },
    { label: "Soprannaturale", genreId: "soprannaturale" },
    { label: "Slice of Life", genreId: "slice-of-life" },
  ],
};
